### ISSUE TITLE
Abandoned? No release with jsonb support after over a year.

### ISSUE THREAD

**Issue by filipncs** [remodoy/clj-postgresql#11]
Looks like there hasn't been a release after the addition of jsonb support. Anything in particular holding this back?

If the project is abandoned or you're looking for someone else to push it along, you should update the readme. This is still one of the highest ranked search results for json type support in postgresql.

**Comment by gseaton** [comment]
DrTom did some work on the types.clj (12/2014) to support :jsonb in the map->parameter multimethod (ln# 104).

The fix is NOT in 0.4.0 version (as stated in the README.md file), but in 0.6.0-SNAPSHOT in clojars, so adjust your project.clj accordingly.

[clj-postgresql "0.6.0-SNAPSHOT"]

**Comment by AlJohri** [comment]
Seems like the latest commit was 2 weeks ago. cc @jkjuopperi

**Comment by jkjuopperi** [comment]
Thank you for your patience. Getting my premature baby girl through the beginning was a bit intensive but all went well and I'm back now. I'll try to find time to push clj-postgresql forward. Contributions are welcome.
