### ISSUE TITLE
Why bonecp and not hicarycp?

### ISSUE THREAD

**Issue by atsman** [remodoy/clj-postgresql#13]
Hi, i am interested why do u use bonecp instead of hicarycp? Last one much more performant.

**Comment by jkjuopperi** [comment]
I only found c3p0 and bonecp when I was first doing this. The original code was used quite a while before publishing so it might also predate hikaricp.

HikariCP sounds good. Thanks for the hint. I'll take I look migrating to HikariCP when I have time. Also contributions are much appreciated so feel free not to wait for me :)

**Comment by Atsman** [comment]
@jkjuopperi ok good to hear, maybe will migrate myself

**Comment by philjackson** [comment]
Very late to this issue, but I've submitted a simple PR: https://github.com/remodoy/clj-postgresql/pull/18

**Comment by jkjuopperi** [comment]
@philjackson thank you for the PR
