### ISSUE TITLE
Convert sequences to JSONB

### ISSUE THREAD

**Issue by podviaznikov** [remodoy/clj-postgresql#4]
Right now only maps are converted to JSON and JSONB.
Would be good to have the same functionality for the sequences.

**Comment by thron7** [comment]
I had the same problem and provided a pull request: https://github.com/remodoy/clj-postgresql/pull/14 .
As a work-around, you can provide the missing multimethods in your own code.

**Comment by Atsman** [comment]
@jkjuopperi can u please deploy it to clojars?

**Comment by Atsman** [comment]
I guess we can close it, as code is already in the master

**Comment by Atsman** [comment]
???

**Comment by georgejdanforth** [comment]
Has this fix been deployed to clojars? I'm having the same issue when trying to insert a sequence as JSON:
```
PSQLException Can't infer the SQL type to use for an instance of clojure.lang.PersistentVector. Use setObject() with an explicit Types value to specify the type to use.  org.postgresql.jdbc.PgPreparedStatement.setObject (PgPreparedStatement.java:967)
```
